using System.Reflection;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Reflection.AssemblyVersionAttribute("0.0.0.1")]
[assembly: AssemblyCopyrightAttribute("Copyright 2013 Spring2 Technologies")]
[assembly: AssemblyCompanyAttribute("Spring2 Technologies")]
[assembly: AssemblyProductAttribute("Spring2.Common")]

